#!/usr/bin/env python3

desc = """
BiEdit v0.0.1 

    List server options and usage:
        ./biedit -h

    List conversion options and usage:
        ./biedit convert -h
"""

import os
import sys
import json
import time
import optparse
import subprocess
import webbrowser

from pathlib import Path
from urllib.parse import urlparse, parse_qs
from http.server import HTTPServer, SimpleHTTPRequestHandler 

import asyncio
async_run = asyncio.get_event_loop().run_until_complete

def commandline():

  default_port = 8090
  app_dir = os.path.dirname(os.path.abspath(__file__))


  if len(sys.argv) > 1 and sys.argv[1] == "convert":

    outformats = {
      'pdf': '.pdf',
      'latex': '.tex',
      'latex-body': '.body.tex',
      'html': '.html',
      'html-body': '.body.html',
      'html-tagged-body-raw': '.tagged.body.raw.html',
      'html-tagged-body': '.tagged.body.html',
      'html-tagged': '.tagged.html',
    }

    allowed = list(outformats.keys())
    allowed_str = "|".join(allowed)
    parserc = optparse.OptionParser(add_help_option=False)
    parserc.add_option('-f', '--outformat',
                      default=None,
                      help='One of ' + "|".join(allowed_str))
    parserc.add_option('-o', '--outfile',
                      default=None,
                      help='Output file name (default: path/to/infile.pdf)')
    parserc.add_option('-i', '--infile',
                      help='Input file name')
    parserc.add_option('-h', '--help',
                      dest='help',
                      action='store_true',
                      help='Show this help message and exit')
    parserc.add_option("-l", "--loglevel",
                      help="Log level " + "(error, default, debug) [%s]" % "default",
                      default="default")
    parserc.add_option("-d", "--dir",
                      help="Repository directory " + "[%s]" % os.getcwd(),
                      default=os.getcwd())

    cusage =  f"\nbiedit convert <infile.md|'PATTERN'.md>\n"
    cusage += f"\t [-o outfile.{{{allowed_str}}}]"
    cusage += "\n\tor"
    cusage += f"\n\t [-f {{PATTERN|{allowed_str}}}]"

    (options, args) = parserc.parse_args()
    options = vars(options)

    if options['infile'] is None:
      if len(args) > 1:
        options['infile'] = args[1]
      else:
        print("Error: No file to convert given.\nUsage: " + cusage)
        sys.exit(1)

    if options['outformat'] is None:
      if options['outfile'] is None:
        filename, ext = os.path.splitext(options['infile'])
        options['outfile'] = filename
        options['outformat'] = allowed
      else:
        filename, ext = os.path.splitext(options['outfile'])
        if ext == "":
          options['outformat'] = allowed
        else:
          options['outformat'] = [ext[1:]]
    else:
      options['outformat'] = options['outformat'].split(",")
      if options['outfile'] is None or len(options['outfile']) == 0:
        filename, ext = os.path.splitext(options['infile'])
        options['outfile'] = filename

    for fmt in options['outformat']:
      if fmt not in allowed:
        print(f'Error: outformat "{fmt}" does not match one of {allowed}')
        sys.exit(1)

    options['port'] = default_port
    options['open'] = False
    options['dir'] = os.getcwd()
    options['app'] = os.getcwd()
    options['no_html'] = True
    options['convert'] = True
    if options['help']:
      parserc.set_usage()
      parserc.print_help()
      sys.exit(0)
  else:
    parsers = optparse.OptionParser(add_help_option=False)
    parsers.add_option('-h', '--help',
                      dest='help',
                      action='store_true',
                      help='Show this help message and exit')
    parsers.add_option("-l", "--loglevel",
                      help="Log level " + "(error, default, debug) [%s]" % "defaut",
                      default="default")
    parsers.add_option('-o', '--open',
                      action='store_true',
                      help='Open web page')
    parsers.add_option("-p", "--port",
                      type="int",
                      help="Server port " + "[%d]" % default_port,
                      default=default_port)
    parsers.add_option("-d", "--dir",
                      help="Repository directory " + "[%s]" % os.getcwd(),
                      default=os.getcwd())
    parsers.add_option("-r", "--remote",
                      help="Remote repository for push",
                      default="")
    if False:
      parsers.add_option("-s", "--symlink",
                        action='store_true',
                        help="Create symlinks (ln -s file.html file).")
    parsers.add_option("--no-html",
                      action='store_true',
                      help="Do not save file.html when file.md saved.",
                      default=False)
    parsers.add_option("--no-pdf",
                      action='store_true',
                      help="Do not save file.pdf when file.md saved.",
                      default=True)
    parsers.add_option("-a", "--app",
                      help="Application location " + \
                           "[%s]".format(app_dir),
                      default=app_dir)

    (options, args) = parsers.parse_args()
    options = vars(options)
    options['convert'] = False

    if options['help']:
      print(desc)
      print("-- Server --")
      parsers.print_help()
      print("")
      print("-- Conversion --")
      parserc.set_usage(cusage)
      parserc.print_help()
      sys.exit(0)

    repository = repository_info(options['remote'])
    if repository is not None:
      print("Remote: " + repository['url'])
      print("Credentials: " + str(repository['credentials']))

  return options


def set_signals():
  # https://github.com/miyakogi/pyppeteer/issues/61#issuecomment-379781534
  import signal, psutil, os

  def kill_child_processes(parent_pid, sig=signal.SIGTERM):
    try:
        parent = psutil.Process(parent_pid)
    except psutil.NoSuchProcess:
        return
    children = parent.children(recursive=True)
    if len(children) > 0:
        print("")
    for process in children:
        print("Killing process named '{}' with pid = {}" \
            .format(process.name(), process.pid))
        try:
            process.send_signal(sig)
        except:
            pass # Process was already killed.

  def handler_stop_signals(signum, frame):
    kill_child_processes(os.getpid())
    sys.exit(0)

  signal.signal(signal.SIGINT, handler_stop_signals)
  signal.signal(signal.SIGTERM, handler_stop_signals)


def check_deps():
  try:
    from pyppeteer import launch
  except ImportError:
    print("Generating PDF requires the pyppeteer package. " \
          + "Install it first.")


class MD2HTML:

    def __init__(self):
      check_deps()
      return None


    async def start(self):

      from pyppeteer import launch

      if hasattr(self, 'page'):
        return

      start = time.time()
      browser = await launch(args=["--no-sandbox"], 
                  headless=True,
                  handleSIGTERM=False,
                  handleSIGINT=False,
                  handleSIGHUP=False
              )

      self.browser = browser
      self.page = await browser.newPage()
      print('%.4fs: browser launch time' % (time.time() - start))

      return self


    async def write(self, infile, outfile, outformat):

      def console(msg):
        print("Browser console: " + msg.text)
      self.page.on('console', console)

      url = "http://localhost:" + str(options['port'])
      url = url + "/" + infile + "!#view=" + outformat

      start = time.time()
      print("Starting page.goto " + infile + "!#view=" + outformat)
      await self.page.goto(url, {"waitUntil": "domcontentloaded"})
      print("%.4fs: Finished page.goto" % (time.time() - start))

      start = time.time()
      print("Starting page.reload()")
      # TODO: reload only needed when hash changes (when mulitple calls)
      await self.page.reload() 
      print("%.4fs: Finished page.reload" % (time.time() - start))

      # Screenshot needed b/c it forces DOM rendering to complete before
      # evaluation call.
      start = time.time()
      outpng = outfile + '.png'
      print("Starting page.screenshot. outpng = " + outpng)
      await self.page.screenshot({'path': outpng})
      print("%.4fs: Finished page.screenshot" % (time.time() - start))

      start = time.time()
      outdata = await self.page.evaluate(f'''() => {{
          return ace.edit("{outformat}").getValue()
      }}''')
      print(f"%.4fs: {outformat} generation time" % (time.time() - start))
      with open(outfile, "w") as f:
        f.write(outdata)


    def convert(self, infile, outfile, outformat):

      async def task(infiles, outfile, outformat):

        start = time.time()
        await self.start()

        for outformat in options['outformat']:
          outfmt_split = outformat.split("-")
          if len(outfmt_split) == 1:
            outext = outfmt_split[0]
          else:
            outext = ".".join(outfmt_split[1:]) + "." + outfmt_split[0]

          for infile in infiles:
            if options['outfile'].endswith("/"):
              filename, ext = os.path.splitext(infile)
              filename = filename.split(os.sep)[-1]
              outfile = options['outfile'] + filename + '.' + outext
            else:
              outfile = options['outfile'].rsplit('.', maxsplit=1)[0] + '.' + outext

            print("Converting: " + infile + " to " + outformat)
            await self.write(infile, outfile, outformat)
            print("Wrote: " + outfile)

        print("-------\n%.4fs: total time" % (time.time() - start))
        await self.browser.close()

      def run():
        import glob
        infiles = glob.glob(options['infile'])
        if len(infiles) == 0:
          print(f"glob.glob('{options['infile']}') returned no matches")
          sys.exit(1)

        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        loop.run_until_complete(task(infiles,outfile,outformat))
        loop.close()
        from _thread import interrupt_main
        interrupt_main()

      import threading
      t = threading.Thread(target=run, daemon=True)
      t.start()


class HTML2PDF:

  def __init__(self):
    check_deps()
    return None

  async def start(self):
    from pyppeteer import launch

    if hasattr(self,'page'):
      return

    start = time.time()
    browser = await launch(args=["--no-sandbox"], 
                headless=True,
                handleSIGTERM=False,
                handleSIGINT=False,
            )
    self.page = await browser.newPage()
    end = time.time()
    print('Browser launch time: %.4f s' % (end - start))

    return self


  async def convert(self, html, outfile):
    # Based on
    # https://www.programcreek.com/python/example/119403/pyppeteer.launch

    if not html.startswith("http"):
      html = Path(html).resolve()
      html = f"file:///{html}"

    page_margins = {
        "left": "0",
        "right": "0",
        "top": "0",
        "bottom": "0"
    }
    start = time.time()

    def cp(msg):
      print(msg.text)
    self.page.on('console', cp)

    #await self.page.goto(html, waitUntil=['load', 'domcontentloaded', 'networkidle0', 'networkidle2']);
    # waitUntil causes a fairly long delay but is needed for images
    # Doing a reload fixes problem of blank PDF (b/c rendering not complete)
    # See also https://swizec.com/blog/how-to-wait-for-dom-elements-to-show-up-in-modern-browsers
    # and https://stackoverflow.com/questions/15875128/is-there-element-rendered-event
    # https://miyakogi.github.io/pyppeteer/reference.html#pyppeteer.page.Page.goto
    # https://stackoverflow.com/questions/52497252/puppeteer-wait-until-page-is-completely-loaded
    print("Opening " + html)
    await self.page.goto(html)#,waitUntil=['domcontentloaded'])
    await self.page.emulateMedia("print")
    await self.page.reload() # Needed. See above about blank PDF.
    await self.page.pdf({
            "path": outfile,
            "margin": page_margins
        })
    print("PDF generation time: %.4f s" % (time.time() - start))


def dirwalk(selected, outfmt='html'):

    print("Creating options drop-down with '" + selected + "' selected.")

    def json(selected):
      base = os.path.abspath(os.getcwd())
      json_list = []
      for root, dirs, files in os.walk(base):
        path = root.split(os.sep)
        if len(path) == 1 and path[0] == '.':
          continue
        if '.git' in path:
          continue

        json_list.append({'title': path[-1], 'isSelectable': 'false', 'subs': []})
        for file in files:
          json_list[-1]['subs'].append({'title': file})
      return json_list

    if outfmt == 'json':
        return json(selected)

    base = os.path.abspath(os.getcwd())
    Nb = len(base.split(os.sep)) # Number of blanks

    html = '';
    if selected == '':
      html = '<option selected value="">File</option>'

    for root, dirs, files in os.walk(base):
      dirs.sort()

      path = root.split(os.sep)
      if len(path) == 1 and path[0] == '.':
        continue
      if '.git' in path:
        continue

      root = root.replace(base, "")
      indent = 4*(len(path) - Nb)*'&nbsp;'
      dir = root.split("/")[-1]
      if dir == '':
        dir = '.'
      html = html + '<optgroup label="' + indent + dir + '">'
      files.sort()
      for file in files:
        if not (file.endswith(".md") or file.endswith(".css")):
          continue
        value = root + '/' + file
        if selected.startswith(value[1:]):
          start = '<option selected value="' + value[1:] + '">'
        else:
          start = '<option value="' + value[1:] + '">'

        end = '</option>'
        #print((len(path) - Nb) * '&nbsp;' + file)
        if indent == "":
          html = html + start + file + end
        else:
          html = html + start + indent + '' + file + end
      html = html + '</optgroup>'

    return html


def repository_info(url_cl):
    import re

    gitPath = os.path.join(os.getcwd(),'.git')

    def rm_credentials(url):
        return re.sub(r'\/\/(.+@)', '//', url)

    def normalize(url):
        return re.sub(r'\/$|\.git$|\.git\/', '', url)

    credentials_cl = rm_credentials(url_cl) != url_cl
    url = None 
    credentials = False
    if os.path.exists(gitPath):
        configFile = os.path.join(gitPath,'config')
        if configFile:
            file1 = open(configFile, 'r')
            lines = file1.readlines()
            for line in lines:
                line = line.strip()
                if line.startswith('url = '):
                    line = line.replace('url = ', '')
                    credentials = True
                    url = rm_credentials(line)
                    if url == line:
                        print('No credentials in URL in ./git/config. ' + \
                              'Push from BiEdit will not be possible.')

    if url and url_cl:
        if normalize(url) != normalize(url_cl):
            raise ValueError('Repository URL given on command line \n   ' \
                                + url_cl \
                                + '\ndoes not match URL in .git/config\n   ' \
                                + url)


    if url:
        return {'url': normalize(rm_credentials(url)), 'credentials': credentials}
    if url_cl:
        return {'url': normalize(rm_credentials(url_cl)), 'credentials': credentials_cl}


def convert():
  md2html = MD2HTML()
  md2html.convert(options['infile'], options['outfile'], options['outformat'])

# https://stackoverflow.com/a/16838003
class CallbackHTTPServer(HTTPServer):

  def server_activate(self):
    HTTPServer.server_activate(self)
    if options["convert"] == True:
      print("Server activated. Calling convert().")
      convert()


class HTTPRequestHandler(SimpleHTTPRequestHandler):

  def log_message(self, format, *args):
    if options["loglevel"] == "debug":
      print("%s - - [%s] %s" % \
        (self.client_address[0], self.log_date_time_string(), format%args))

  def end_headers(self):
    # Overrides default end_headers().
    # This will not delete the default Content-Type header
    # of 'application/octet-stream' that appears for these two cases,
    # but it seems clients use the last Content-Type in the header.
    if self.path.endswith('.md'):
      self.send_header("Content-type", "text/markdown; charset=utf-8")
    if not "." in os.path.basename(self.path):
      self.send_header("Content-type", "text/html; charset=utf-8")
    SimpleHTTPRequestHandler.end_headers(self)

  def translate_path(self, path):
    # https://stackoverflow.com/a/46332163
    path = SimpleHTTPRequestHandler.translate_path(self, path)
    if self.path.startswith("/.biedit/"):
      relpath = os.path.relpath(path, os.getcwd())
      fullpath = os.path.join(options['app'], relpath)
      return fullpath
    else:
      return path

  def do_GET(self):

    URL = urlparse(self.path)
    query = parse_qs(URL.query)

    if URL.path.startswith("/.biedit/deps/"):
      return SimpleHTTPRequestHandler.do_GET(self)

    if URL.path == '/' or URL.path[-1] == '!':
      # Trailing ! means "edit"

      # remove leading / and trailing !
      initialFile = URL.path[1:-1]
      if URL.path == '/':
        initialFile == ''

      self.send_response(200)
      self.send_header("Content-type", "text/html; charset=utf-8")
      self.end_headers()

      if initialFile != '' and not os.path.exists(initialFile):
        print('Touching ' + initialFile)
        Path(initialFile).touch()

      initialFile = initialFile.split(os.sep)[-1]

      # TODO: Fetch index.html from repository if not found.
      index = os.path.join(options['app'], 'index.html')
      # TODO: Instead of replacements, create dict and
      # convert to JSON. Then insert.
      with open(index, "rt") as fin:
        data = fin.read()
        print(f"Sending {index} with initialFile = '{initialFile}'")
        data = data.replace("${files}", dirwalk(URL.path[1:-1])) 
        orig = "initialFile: 'index.md'"
        repl = f"initialFile: '{initialFile}'"
        data = data.replace(orig, repl)

      if options['no_html'] == True:
        data = data.replace("noHTML: false", "noHTML: true") 

      if not os.path.exists(".sourcedir"):
        # print("Did not find .sourcedir")
        # Allow creation of file named index.md
        data = data.replace("allowIndexMD: false", "allowIndexMD: true") 

      self.wfile.write(bytes(data, 'utf-8'))
    else:
      if "infile" in query and query["infile"][0].endswith('.html'):
        outfile = URL.path[1:].split("?")[0]
        infile = query["infile"][0][1:]
        print('Generating: ' + outfile + " from " + infile)
        async_run(html2pdf.start())
        async_run(html2pdf.convert(infile, outfile))
        print('Generated: ' + outfile)

      # File has been generated. Hand off request to default do_GET(),
      # which will respond with file.
      return SimpleHTTPRequestHandler.do_GET(self)

  def do_POST(self):

    length = self.headers['content-length']
    post_bytes = self.rfile.read(int(length))
    post = json.loads(post_bytes)

    # Remove leading slash
    file_save = self.path[1:]
    #print("self.path = " + file_save)

    if 'command' in post:

      if post['command'] == 'commit':
        file_base = os.path.splitext(file_save)[0]
        cmd = 'git add ' + file_base + "*"
        cmd = cmd + "; git commit " + file_base + "*" \
                  + " -m '" + post['message'] + "'; echo Done"
      elif post['command'] == 'push':
        repository = repository_info(options['remote'])
        if not repository['credentials']:
          msg = "Cannot push: server not configured with remote repository."
          self.send_error(501, {"Error": msg})
          return
        else:
          cmd = "git push " + options['remote'] + "; echo Done"
      else:
        self.send_response(200)
        self.send_header('Content-type', 'text/html; charset=utf-8')
        self.end_headers()
        return

      self.send_response(200)
      self.send_header('Content-type', 'text/html; charset=utf-8')
      self.end_headers()

      print("Executing " + cmd)
      stream = subprocess.Popen(cmd, shell=True,
                  stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
      while True:
        line = stream.stdout.readline()
        print(line.decode().rstrip())
        self.wfile.write(line)
        if not line:
          break

    elif 'markdown' or 'html' or 'css' or 'latex' in post:

      file_path = os.path.dirname(file_save)
      if file_path != '':
        os.makedirs(file_path, exist_ok=True)

      file_base = os.path.splitext(file_save)[0]

      if 'markdown' in post:
        print("Writing " + os.path.join(options['dir'], file_base + '.md'))
        with open(file_base + '.md', 'w') as fh:
          fh.write(post['markdown'])

      if 'css' in post:
        print("Writing " + os.path.join(options['dir'], file_base + '.css'))
        with open(file_base + '.css', 'w') as fh:
          fh.write(post['css'])

      if 'latex' in post:
        print("Writing " + os.path.join(options['dir'], file_base + '.tex'))
        with open(file_base + '.tex', 'w') as fh:
          fh.write(post['latex'])

      if 'html' in post and post['html'] != '':
        print("Writing " + os.path.join(options['dir'], file_base + '.html'))
        with open(file_base + '.html', 'w') as fh:
          fh.write(post['html'])

        if False:
          if not os.path.exists(file_base) and options['symlink']:
            print("Symlinking " 
                    + os.path.join(options['dir'], file_base + '.html') 
                    + " to " + file_base)
            base = os.path.basename(file_base)
            os.symlink(base + '.html', file_base)

      self.send_response(200)
      self.send_header('Content-type', 'text/html; charset=utf-8')
      self.end_headers()
      self.wfile.write(bytes("Wrote " + file_base + ".{md,html}\n", 'utf-8'))

    else:

      self.send_response(200)
      self.send_header('Content-type', 'text/html; charset=utf-8')
      self.end_headers()
      self.wfile.write(bytes("Nothing to do.\n", 'utf-8'))


mypath = os.getcwd()
for f in os.listdir(mypath):
  if f.endswith(".md") and f.lower() == "index.md":
    index = f
  if f.endswith(".md") and f.lower() == "readme.md":
    readme = f

# TODO: Wrap HTTPRequestHandler in function so that
#       options and html2pdf do not need to be global variables.
options = commandline()
html2pdf = HTML2PDF()

#if options['outformat'] == 'pdf':
  #print('Generating ' + pdf_file)
  #async_run(html2pdf.start())
  #async_run(html2pdf.convert(html_file, pdf_file))
  #print('Generated ' + pdf_file)

set_signals()

os.chdir(options['dir'])

for port in range(options['port'], options['port'] + 10):
  try:
    options['port'] = port
    server = CallbackHTTPServer(('', port), HTTPRequestHandler)
    url = "http://localhost:" + str(port)
    if options['convert'] == False:
      print("Edit files in " + options['dir'] \
          + " at http://localhost:%d/" % port)
    if options['open']:
      webbrowser.open_new(url)
    else:
      if options['convert'] == False:
        print("Use the -o option to open page automatically.")
    server.serve_forever()
  except OSError as err:
    print("Could not start BiEdit on port " \
          + str(port) \
          + ". Trying a different port.")

raise OSError("Could not find an open port. Tried " \
            + str(options['port']) + "-" + str(options['port'] + 9) \
            + ". Specify a different port using the --port" \
            + " command line argument.")

if False:
  import logging
  from watchdog.observers import Observer
  from watchdog.events import LoggingEventHandler

  logging.basicConfig(level=logging.INFO,
                      format='%(asctime)s - %(message)s',
                      datefmt='%Y-%m-%d %H:%M:%S')
  path = sys.argv[1] if len(sys.argv) > 1 else '.'
  event_handler = LoggingEventHandler()
  observer = Observer()
  observer.schedule(event_handler, path, recursive=True)
  observer.start()
  try:
    while True:
      time.sleep(1)
  finally:
    observer.stop()
    observer.join()
