function slug(text, number) {

  util.log(`text=${text}; number=${number}`,'slug',1);

  number = number.trim();

  util.log(`text=${text}; number=${number}`,'slug',1);

  // Remove HTML in heading. See https://stackoverflow.com/a/5002161
  // TODO: Use turndown.js
  var escapedText = text
                        .replace(/<\/?[^>]+(>|$)/g, "")
                        .toLowerCase()
                        .replace(/[^\w|\.]+/g, '-')
                        .replace(/(^-|-$)/,"");
  util.log("escapedText after removing HTML and LaTeX entities:\n"+escapedText,'slug',1);

  if (!escapedText && !number) {
    return;
  }

  if (number && app['TOC']['markdown']['show']) {
    escapedText = escapedText.replace(new RegExp("^" + number + "\s?-?"),"")
    util.log(`text after removal of leading number = ${text}`,'slug',1);
    if (app['TOC']['markdown']['style'] === 'numbered-custom-1') {
      escapedText = escapedText.replace(/([0-9])\.([0-9])/g,"$1$2");
      // Quick fix to use Github-style slug where
      // 1.1 abc -> 11-abc
      // instead of
      // 1.1 abc -> 1.1-abc
      // This is so anchors autogenerated by Github Markdown parser
      // will match what is in custom TOC.
      number = number.replace(/([0-9]*)\.([0-9])/g,"$1$2");
      util.log("escapedText after replacing hyphens in pattern ([0-9]*)-([0-9]):\n"+escapedText,'slug',1);
      escapedText = number.trim() + "-" + escapedText;
    } else {
      escapedText = number.trim() + "-" + escapedText;
    }
  }

  if (escapedText.trim() === "") {
    escapedText = number;
  }

  util.log("Final escapedText = " + escapedText,'slug',1);
  return escapedText;
}